server:
  port: 8080
  tomcat:
    connection-timeout: PT6M

spring:
  application:
    name: springboot-demo
  cloud:
    nacos:
      discovery:
        #nacos 服务地址
        server-addr: localhost:8848
        enabled: true
  session:
    store-type: redis
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 10
        max-wait: 7s
        max-idle: 8
        min-idle: 2
    timeout: 10s


eureka:
  client:
    service-url:
      defaultZone: http://localhost:11111/eureka/